version: '3.8'

services:
  app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=baikal
      - JWT_SECRET=your-secret-key
      - PORT=8080
    depends_on:
      - db
    networks:
      - baikal-network

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=baikal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - baikal-network

volumes:
  postgres_data:

networks:
  baikal-network:
    driver: bridge 